import SwiftUI

/// Open-source packages and model weights Luxicon ships with or downloads,
/// from the bundled acknowledgements.json (regenerated by
/// scripts/generate-notices.sh). Rows open the upstream page in Safari —
/// a user-initiated link-out, same as the giving screen's.
struct AcknowledgementsView: View {
    private struct Entry: Decodable, Identifiable {
        let name: String
        let version: String?
        let license: String
        let url: String
        let copyright: String?
        var id: String { name }
    }

    private struct Acknowledgements: Decodable {
        let packages: [Entry]
        let models: [Entry]
    }

    private let acknowledgements: Acknowledgements? = {
        guard let url = Bundle.main.url(forResource: "acknowledgements",
                                        withExtension: "json"),
              let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(Acknowledgements.self, from: data)
    }()

    var body: some View {
        Form {
            if let ack = acknowledgements {
                Section {
                    ForEach(ack.models) { row($0) }
                } header: {
                    Text("Speech models")
                } footer: {
                    Text("Downloaded from Hugging Face on first use and run entirely on this device. Each model carries its own license.")
                }
                Section {
                    ForEach(ack.packages) { row($0) }
                } header: {
                    Text("Swift packages")
                } footer: {
                    Text("Luxicon itself is MIT-licensed. Full license and notice texts are under License texts below, and in THIRD-PARTY-NOTICES.md in the source repository.")
                }
                Section {
                    NavigationLink("Full license and notice texts") {
                        LicenseTextsView()
                    }
                } header: {
                    Text("License texts")
                }
            } else {
                Text("Acknowledgements are missing from this build.")
                    .foregroundStyle(.secondary)
            }
        }
        .navigationTitle("Acknowledgements")
    }

    @ViewBuilder
    private func row(_ entry: Entry) -> some View {
        if let url = URL(string: entry.url) {
            Link(destination: url) { label(for: entry) }
                .accessibilityHint("Opens the project page in Safari")
        } else {
            label(for: entry)
        }
    }

    private func label(for entry: Entry) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            HStack {
                Text(entry.name)
                    .foregroundStyle(.primary)
                Spacer()
                Text(entry.license)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            if let version = entry.version, !version.isEmpty {
                Text(version)
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }
            if let copyright = entry.copyright {
                Text(copyright)
                    .font(.caption2)
                    .foregroundStyle(.tertiary)
            }
        }
    }
}

/// Full contents of the bundled THIRD-PARTY-NOTICES.md, pushed from the
/// packages section so the App Store binary carries the complete license
/// and NOTICE texts, not just name/version/license-id.
private struct LicenseTextsView: View {
    private static let noticesText: String = {
        guard let url = Bundle.main.url(forResource: "THIRD-PARTY-NOTICES",
                                        withExtension: "md"),
              let text = try? String(contentsOf: url, encoding: .utf8) else {
            return "License texts are missing from this build."
        }
        return text
    }()

    var body: some View {
        ScrollView {
            Text(Self.noticesText)
                .font(.caption.monospaced())
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding()
        }
        .navigationTitle("License Texts")
        .navigationBarTitleDisplayMode(.inline)
    }
}
